<a href="https://colab.research.google.com/github/Dhawaldwivedi/Bca-5th-sem-AI-mmdu/blob/main/ai-ml2-g3/Loops_data_structures_and_numpy_bca.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hi")

hi


# Loops

In [2]:
## for loop
for i in range(2,10):
  print(i)


2
3
4
5
6
7
8
9


In [5]:
# step size  # range(start index , end+1 index , step size)
for i in range(10,2,-1):
  print(i)

10
9
8
7
6
5
4
3


In [ ]:
for i in range(2,11):
  print(i)

2
3
4
5
6
7
8
9
10


In [ ]:
# for loop through string
s = "mmdu"
for i in s:
  print(i)

m
m
d
u


In [ ]:
# while loop
count = 0
while count<5:
  print(count)
  count= count+1

0
1
2
3
4


In [ ]:
# break statements
for i in range(20):
  print(i)
  if i==5:
    break

0
1
2
3
4
5


In [ ]:
# continue
for i in range(10):
  if i==5:
    continue
  print(i)


0
1
2
3
4
6
7
8
9


In [ ]:
## Nested loopss
## a loop inside a loop

for i in range(3):
    for j in range(2):
        print(f"i:{i} and j:{j}")

i:0 and j:0
i:0 and j:1
i:1 and j:0
i:1 and j:1
i:2 and j:0
i:2 and j:1


In [6]:
i = 5
j = 8
print(f"value of i is {i} and j is {j}")

value of i is 5 and j is 8


In [ ]:
## Example- Prime numbers between 1 and 100

In [10]:
''' *****
    *****
    *****
    *****
    *****  '''
for i in range(5):         # number of rows
  for j in range(5):
    print("*",end ="")
  print()         # value in each row

''' *
    **
    ***
    ****
    *****  '''
for i in range(5):         # number of rows
  for j in range(i):
    print("*",end ="")
  print()

*****
*****
*****
*****
*****

*
**
***
****


In [ ]:
'''  *****
     ****
     ***
     **
     *  '''

'  *****\n     ****\n     ***\n     **\n     *  '

# Data Structures

In [ ]:
lst=[]
print(type(lst))

<class 'list'>


In [11]:
### Accessing List Elements

fruits=["apple","banana","cherry","kiwi","gauva"]

In [12]:
print(fruits[0])
print(fruits[2])
print(fruits[4])
print(fruits[-1])

apple
cherry
gauva
gauva


In [13]:
## Modifying The List elements
fruits[1]="watermelon"
print(fruits)

['apple', 'watermelon', 'cherry', 'kiwi', 'gauva']


In [14]:
## List Methods

fruits.append("orange")
print(fruits)

['apple', 'watermelon', 'cherry', 'kiwi', 'gauva', 'orange']


In [15]:
fruits.insert(1,"watermelon")
print(fruits)
print(fruits.index("watermelon"))

['apple', 'watermelon', 'watermelon', 'cherry', 'kiwi', 'gauva', 'orange']
1


In [16]:
fruits.remove("watermelon") ## Removing the first occurance of an item
print(fruits)

['apple', 'watermelon', 'cherry', 'kiwi', 'gauva', 'orange']


In [ ]:
fruits.index("watermelon")

1

In [17]:
## Remove and return the last element
popped_fruits=fruits.pop()
print(popped_fruits)
print(fruits)

orange
['apple', 'watermelon', 'cherry', 'kiwi', 'gauva']


In [ ]:
index=fruits.index("cherry")
print(index)

3


In [18]:
fruits.sort()
fruits

['apple', 'cherry', 'gauva', 'kiwi', 'watermelon']

In [19]:
fruits.reverse()
fruits ## REverse the list

['watermelon', 'kiwi', 'gauva', 'cherry', 'apple']

In [26]:
fruits[::-1]

['apple', 'cherry', 'gauva', 'kiwi', 'watermelon']

In [27]:
fruits.clear() ## Remove all items from the list

print(fruits)

[]


In [28]:
## List comprehension

[x**2 for x in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

Tuples

In [ ]:
lst = list([1,2,3,4])

In [29]:
numbers=tuple([1,2,3,4,5,6])
numbers

(1, 2, 3, 4, 5, 6)

In [30]:
mixed_tuple=(1,"Hello World",3.14, True)
print(mixed_tuple)

(1, 'Hello World', 3.14, True)


In [ ]:
print(numbers[2])
print(numbers[-1])

3
6


In [ ]:
## Tuple Operations

concatenation_tuple=numbers + mixed_tuple
print(concatenation_tuple)

(1, 2, 3, 4, 5, 6, 1, 'Hello World', 3.14, True)


In [ ]:
lst=[1,2,3,4,5]
print(lst)

lst[1]="Krish"
print(lst)

[1, 2, 3, 4, 5]
[1, 'Krish', 3, 4, 5]


In [ ]:
numbers[1]="Krish"

TypeError: 'tuple' object does not support item assignment

In [ ]:
## Packing and Unpacking tuple
## packing
packed_tuple=1,"Hello",3.14
print(packed_tuple)

(1, 'Hello', 3.14)


In [ ]:
##unpacking a tuple
a,b,c=packed_tuple

print(a)
print(b)
print(c)

1
Hello
3.14


In [ ]:
## Unpacking with *
numbers=(1,2,3,4,5,6)
first,*middle,last=numbers
print(first)
print(middle)
print(last)

1
[2, 3, 4, 5]
6


In [32]:
## Nested List
lst=[[1,2,3,4],[6,7,8,9],[1,"Hello",3.14,"c"]]
lst[0][:3]

[1, 2, 3]

In [ ]:
nested_tuple = ((1, 2, 3), ("a", "b", "c"), (True, False))

## access the elements inside a tuple
print(nested_tuple[0])
print(nested_tuple[1][2])

(1, 2, 3)
c


Sets

In [33]:
my_set={1,2,3,4,5} # if empty its a dict
print(my_set)
print(type(my_set))

{1, 2, 3, 4, 5}
<class 'set'>


<class 'dict'>


In [ ]:
my_empty_set=set([1,2,3,6,5,4,5,6]) # Contains unique values
print(my_empty_set)

{1, 2, 3, 4, 5, 6}


In [34]:
## Basics Sets Operation
## Adiing and Removing Elements
my_set.add(7)
print(my_set)
my_set.add(7)
print(my_set)

{1, 2, 3, 4, 5, 7}
{1, 2, 3, 4, 5, 7}


In [36]:
# remove
my_set.remove(6)
my_set

KeyError: 6

In [38]:
#discard
my_set.discard(8)
my_set

{1, 2, 3, 4}

In [ ]:
my_set

{1, 2, 3, 4}

In [40]:
### Counting Unique words in text
text="In this tutorial we are discussing about sets this we are "
words = text.split()
print(words)
uni = set(words)
print(len(uni))

['In', 'this', 'tutorial', 'we', 'are', 'discussing', 'about', 'sets', 'this', 'we', 'are']
8


Dictionary

In [41]:
student={"name":"Krish","age":32,"grade":24}
print(student)
print(type(student))

{'name': 'Krish', 'age': 32, 'grade': 24}
<class 'dict'>


In [42]:
# Single key is slways used
student={"name":"Krish","age":32,"grade":24,"name":"gfg"}
print(student)

{'name': 'gfg', 'age': 32, 'grade': 24}


In [49]:
## accessing Dictionary Elements
student["city"]

KeyError: 'city'

In [51]:
## Accessing using get() method
student.get("name","not available")

'gfg'

In [52]:
student["age"]=33  ##update value for the key
print(student)
student["address"]="India" ## added a new key and value
print(student)

{'name': 'gfg', 'age': 33, 'grade': 24}
{'name': 'gfg', 'age': 33, 'grade': 24, 'address': 'India'}


In [53]:
del student['grade'] ## delete key and value pair

In [56]:
# keys and values function
student.items()

dict_items([('name', 'gfg'), ('age', 33), ('address', 'India')])

In [57]:
# nested dictionaries
## Nested Disctionaries
students={
    "student1":{"name":"Krish","age":32},
    "student2":{"name":"Peter","age":35}
}
print(students)

{'student1': {'name': 'Krish', 'age': 32}, 'student2': {'name': 'Peter', 'age': 35}}


In [58]:
## Practical Examples

## USe a dictionary to count he frequency of elements in list

numbers=[1,2,2,3,3,3,4,4,4,4]
frequency={}
for i in numbers:
  if i in frequency:
    frequency[i]+=1
  else:
    frequency[i]=1
print(frequency)


{1: 1, 2: 2, 3: 3, 4: 4}


In [ ]:
# find unique common elements
list1 = [1, 2, 3, 4, 5, 6, 7, 2]
list2 = [5, 6, 7, 8, 9, 10, 6]

In [ ]:
# Write a program to count the frequency of each character in a given string and store it in a dictionary. Ignore spaces.
# Example Input:
text = "hello world"

# Numpy

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
lst = [[1,2,3],
       [4,5,6],
       [7,8,9]]
lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.ndim #for dimension of array

2

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
# zero and ones array


array([[0., 0., 0.],
       [0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# random function
np.random.random(3,3)


array([[0.9664926 , 0.80839658, 0.59613577],
       [0.30791778, 0.70495566, 0.92666656],
       [0.01913252, 0.12098327, 0.15817355]])

In [ ]:
np.random.randint(6)

0

In [ ]:
# arange
np.arange(1,10,5)

array([1, 6])

In [ ]:
# linspace
np.linspace(1,10,17)

array([ 1.    ,  1.5625,  2.125 ,  2.6875,  3.25  ,  3.8125,  4.375 ,
        4.9375,  5.5   ,  6.0625,  6.625 ,  7.1875,  7.75  ,  8.3125,
        8.875 ,  9.4375, 10.    ])

In [ ]:
# flatten

In [ ]:
p = np.random.random((3,5))
p

In [ ]:
# reshape
np.reshape(p,(5,3))

In [ ]:
# identity matrix


In [ ]:
# arr+1

In [ ]:
int(arr.max())

In [ ]:
int(arr.min())

In [ ]:
int(arr.sum())

In [ ]:
arr.max(axis=0) # column wise

In [ ]:
arr1 =np.array([[2,5,3],
                [4,2,7],
                [3,5,9]])
arr2 =np.array([[1,9,3],
                [2,2,7],
                [7,6,3]])

In [ ]:
arr3 = arr1+arr2

In [ ]:
# sorting

In [ ]:
# stacking and splitting